# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27940048f4a3f257413e407cfce68b6efbee89cde084c9f3be10ba90778d17454ca63dcaa87df42bb1324fef924917a3ff572defb5f6b9c4d7c3e512cccb552

test:
  secret_key_base: 6490db9a5490e0ed374c8e64a91e65ac38c9c1dd4cb094a651362d79b4b53e88a36ece97f65484ba1f4fe527bc532c290e33f62e5690e6cbf53326b6025a5e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
